Feature/KBM 8 create reusable button
mindXcape/KOIB-Frontend pull request #3
Opened 2023-07-11 14:37 UTC by susan8848

# Merge Request

## Summary of change
I have created reusable buttons using Styled components and MUI. Package "classname" was also used as makes it easy to conditionally join CSS classes together. Hover and disabled effect was also enabled in the buttons.
## Mention

Review: @subhashishjungshah  @dipeshkumarsah98 @sarojghalan 

Fixes: KBM-8-create-reusable-button

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [X] Front End (UI) changes
- [ ] Changes in `documentation`

## How did you test
Hover and disabled effect was tested. While hovering in primary button the background  color was changed and cursor was changed to pointer whereas, in disabled button nth was changed as expected.

- [X] Tested the functionality of Buttons

## Checklist

- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] My code follows the style guidelines of this project
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added required tests that prove my fix is effective or that my feature works
- [X] Both New and Existing unit tests pass locally with my changes

2023-07-11 16:56 UTC, dipeshkumarsah98 commented on app/theme-provider.tsx
> +export const KOIBThemeProvider = ({ children }: { children: React.ReactNode }) => (
you have created the theme provider but have you used it ? if not, use it in layout. it should wrap the whole layout 
```
<KOIBThemeProvider>
<body>{children}</body>
</KOIBThemeProvider>

```

2023-07-11 17:02 UTC, dipeshkumarsah98 commented on components/Buttons/style.ts
> +  &.inactiveButton {
we only need one variants for button which is primary button for now. inactive button means when primary button is disabled, inactive button css should be implemented.

2023-07-11 17:05 UTC, dipeshkumarsah98 requested changes
Nice work :+1: . Your PR has been reviewed some of the changes are required which i have commented below. Make sure to resolve them all and ask for re-review when you are done. Thank you

2023-07-12 02:21 UTC, sarojghalan reviewed
Nice work.

2023-07-12 02:21 UTC, sarojghalan commented on app/globals.css
> +  box-sizing: border-box;
HTML elements have some inherent styles provided by the browser's default stylesheet called user agent styles. These default styles can vary slightly between different browsers. 
So try to prevent those styling of like  h1,h2,h3.h4,h5 and many other tags

2023-07-12 14:04 UTC, dipeshkumarsah98 commented on components/Buttons/index.tsx
> +import classNames from 'classnames'
you have to use this convention ` import cn from 'classnames'`

2023-07-12 14:06 UTC, dipeshkumarsah98 commented on components/Buttons/index.tsx
> +function KOIButton({ children, disabled, handler, className, variant, width }: KOIButtonProps) {
What will happen when you don't provide `className and variant` in the props. It will add undefined as the `classNames` to StyledKOIButton. So solve this error

2023-07-12 14:08 UTC, dipeshkumarsah98 commented on components/Buttons/index.tsx
> +      width={width}
The logic you are trying is correct but this doesn't work. Check your error while providing width. Hint: you can find solution in [transient](https://medium.com/@probablyup/introducing-transient-props-f35fd5203e0c)

2023-07-12 14:10 UTC, dipeshkumarsah98 commented on components/Buttons/style.ts
> +  width: ${(props) => (props.width ? props.width + 'px' : '289px')};
This convention is wrong. Use or operator `||` while validating width.

2023-07-12 14:10 UTC, dipeshkumarsah98 commented on components/Buttons/type.ts
> +  width: number
width should be optional.

2023-07-13 00:41 UTC, subhashishjungshah commented
퉷

2023-07-13 00:41 UTC, closed without merging